server:
  port: 8082
some:
  config: Some Configuration Data
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Bingbong123$
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to Daily Code Buffer from yml!!